# Generated by Django 4.0.5 on 2022-06-22 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя проекта', max_length=80, unique=True, verbose_name='Имя проекта')),
                ('slug', models.SlugField(help_text='Slug проекта', max_length=80, unique=True, verbose_name='Slug проекта')),
                ('url_repository', models.URLField(help_text='Ссылка на репозиторий проекта', max_length=500, verbose_name='Ссылка на репозиторий проекта')),
                ('description', models.TextField(help_text='Описание проекта', verbose_name='Описание проекта')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Подпись к изображению', max_length=60, unique=True, verbose_name='Подпись к изображению')),
                ('image', models.ImageField(help_text='Изображение к проекту', upload_to='project_image', verbose_name='Изображение к проекту')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='Проект', on_delete=django.db.models.deletion.CASCADE, to='mainapp.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Изображение к проекту',
                'verbose_name_plural': 'Изображения к проектам',
                'ordering': ('name',),
            },
        ),
    ]
